### ISSUE TITLE
Create EIP-10 describing PoW changes for hard-fork

### ISSUE THREAD

**Issue by aslesarenko** [ergoplatform/eips#15]
This is to specify all the necessary changes in PoW part of ergo protocol.
The current Ergo Protocol v1 should be used as baseline.

**Comment by kushti** [comment]
@aslesarenko EIP is done, whether it is accepted or not, this is issue seems to be not outdated anyway, let's close it?

**Comment by kushti** [comment]
@aslesarenko Autolykos 2 described in https://docs.ergoplatform.com/ErgoPow.pdf . I propose to close this issue then
