### ISSUE TITLE
[EIP-0004] Ergo tokens - decimals value

### ISSUE THREAD

**Issue by gagarin55** [ergoplatform/eips#18]
Why decimals value encoded as a string in token issuing transaction?

**Comment by gagarin55** [comment]
@catena2w

**Comment by catena2w** [comment]
To unify the registers' encoding and simplify apps development and integration.

**Comment by kushti** [comment]
@catena2w @gagarin55 btw, in the reference client, decimals encoded as IntConstant. It was done many months before EIP-4, thus EIP-4 broke the representation of tokens issued before it. It seems that currently the best option is to update the node, thus I've created an issue: https://github.com/ergoplatform/ergo/issues/1142 .
